### ISSUE TITLE
Fix Models

### ISSUE THREAD

**Issue by vitalii-pokrivchak** [jarvis-technologies/mix-api#16]
### `@JoinColumn(name='user_id'` is correctly

**Comment by Duvie-Gazda** [comment]
We don't need to do in such way, because spring boot automatically convert user to user_id. And if we write user_id it will be searching for the `user_id_id`. Your variant is correct too, but we can use like this and it will work with any problem

**Comment by vitalii-pokrivchak** [comment]
@Duvie-Gazda show errors when starting applications

**Comment by Duvie-Gazda** [comment]
@vitalii-pokrivchak  OK I did not see any error Maybe we have some different configurations. But ok I`ll change them for  =)

**Comment by Duvie-Gazda** [comment]
But really now after I have changed to your example I begin to receive too many errors
